-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm'

local config = wezterm.config_builder()

config.font = wezterm.font_with_fallback {
  { family = "JetBrains Mono", weight = "Medium" },
  "Noto Sans Mono CJK JP",
}
config.font_size = 13

config.keys = {
  {
    key = "V",
    mods = "CTRL|SHIFT",
    action = wezterm.action.PasteFrom "Clipboard",
  },
}

config.color_scheme = "Noctalia"
config.disable_default_key_bindings = true
config.disable_default_mouse_bindings = true
config.enable_tab_bar = false
config.force_reverse_video_cursor = true
config.initial_cols = 100
config.initial_rows = 32
config.window_padding = {
  left = 0,
  right = 0,
  top = 0,
  bottom = 0,
}

return config

